name: macOS sed File Modification

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the `main` branch

jobs:
  sed-replace:
    runs-on: macos-latest  # macOS environment

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Checkout the repository

    - name: Create a file
      run: |
        echo "This is an example file with some text." > example.txt
        echo "Add some more text here for testing." >> example.txt
        cat example.txt  # Display the content of the file to verify

    - name: Perform sed replacement
      run: |
        ls
        sed -i"" 's/example/modified/' example.txt
        cat example.txt 
        ls
